# theme: jekyll-theme-leap-day

# Site settings
title: Thought Leaders
email: jegonzal@berkeley.edu
author:
description: Conversations with Thought Leaders in Technology


baseurl: /thought-leaders-fa20

# Build settings
# permalink: :title/
sass:
  sass_dir: css

