# theme: jekyll-theme-leap-day

# Site settings
title: AI-Sys Fa20
email: jegonzal@berkeley.edu
author:
description: AI-Sys Fa20 Course Website


baseurl: /cs294-ai-sys-fa20

# Build settings
# permalink: :title/
sass:
  sass_dir: css

